version: "3.9"
services:
  mongodb:
    image: mongo:4.4.6
    container_name: meu-mongo
    networks:
      - compose-bridge

  node-app-books:
    image: robsonteixeira/node-app:1.1
    container_name: node-app-books
    networks:
      - compose-bridge
    ports:
      - 3000:6000
    depends_on:
        - mongodb

networks:
  compose-bridge:
    driver: bridge